name: tests
on:
  push: { branches: ["master", "main"] }
  pull_request: { branches: "*" }

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo
      - name: Build
        run: cargo +stable build --workspace --all-targets --features indexmap,json,toml,yaml --color=always
      - name: Test
        run: cargo +stable test --workspace --all-targets --features indexmap,json,toml,yaml --color=always
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-targets --features indexmap,json,toml,yaml
      - name: Install miri
        run: rustup +nightly component add miri
      - name: Run miri
        run: cargo +nightly miri test --workspace --all-targets --features indexmap,json,toml,yaml --color=always
