name: tests
on:
  push: { branches: ["master", "main"] }
  pull_request: { branches: "*" }

jobs:
  build_and_test:
    name: Build and test
    runs-on: fizyr
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets --all-features --color=always
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --all-targets --all-features --color=always
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-targets --all-features
      - name: Cleanup
        uses: actions-rs/cargo@v1
        with:
          command: sweep
          args: --maxsize 5120 -r
